#!/usr/bin/with-contenv bash

# config instructions
AgentInstallPrefix=/opt/Okta/OktaLDAPAgent
. $AgentInstallPrefix/scripts/defs.sh

if [ ! -f $AgentInstallPrefix/conf/logback.xml ]; then
    cp $AgentInstallPrefix/logback-default.xml $AgentInstallPrefix/conf/logback.xml
fi

configure_instructions()
{
    echo
    echo "Please configure your Okta LDAP Agent by running the script"
    echo "$AgentInstallPrefix/scripts/configure_agent.sh"
    echo
    echo "Docker command example:"
    echo "docker run -it --rm --entrypoint $AgentInstallPrefix/scripts/configure_agent.sh -v \$(pwd)/conf:$AgentInstallPrefix/conf nightah/okta-ldap-agent"
    echo
}

if [ ! -f $ConfigFile ]; then
    echo "Config file $ConfigFile not readable."
    configure_instructions
    exit 1
fi

# permissions
chown -R abc:abc \
	/opt/Okta/OktaLDAPAgent